### ISSUE TITLE
Feature request: shift enter multiline input

### ISSUE THREAD

**Issue by nouun** [rigormorrtiss/discordo#146]
Title is pretty self explanatory. It would be nice to be able to shift enter to do multiline input.

**Comment by ghost** [comment]
The [`tview.InputField`](https://pkg.go.dev/github.com/rivo/tview#InputField) widget is very basic; it only supports single-line input and some bare functionality. There is an [open issue for `TextArea` widget](https://github.com/rivo/tview/issues/594) for multi-line input. Unfortunately, it has been a while since the issue has been opened and I don't see the `TextArea` widget being implemented anytime soon.

**Comment by nouun** [comment]
Would you be open to a PR which includes [#447](https://github.com/rivo/tview/pull/447)? It contains all the basic features that would be needed.
