### ISSUE TITLE
desktop notifications via dbus or beeep

### ISSUE THREAD

**Issue by sewnie** [rigormorrtiss/discordo#240]
https://github.com/ayntgl/discordo/issues/121 was mainly referencing dunst, which it's only possible way to communicate to with notifiactions is with dbus, and with the beeep library it should be straight-forward i'd assume.

tl;dr use beeep as it can support dbus, which means native system notifictations.

alternatively; have a FIFO/file for discordo to put notifiactions into, which can be read by a wrapper to send to a notification handler (eg. herbe, xnotify, dunst (without dbus!))

**Comment by ghost** [comment]
For cross-compatibility, beeep is a better choice since it supports all major platforms, while dbus is limited to Linux.

**Comment by sewnie** [comment]
after looking at strace it doesn't seem to even attempt to send a notification

**Comment by sewnie** [comment]
```
method call time=1665943865.546995 sender=:1.366 -> destination=org.freedesktop.DBus serial=1 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=Hello
method return time=1665943865.547006 sender=org.freedesktop.DBus -> destination=:1.366 serial=1 reply_serial=1
   string ":1.366"
signal time=1665943865.547013 sender=org.freedesktop.DBus -> destination=(null destination) serial=483 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameOwnerChanged
   string ":1.366"
   string ""
   string ":1.366"
signal time=1665943865.547022 sender=org.freedesktop.DBus -> destination=:1.366 serial=2 path=/org/freedesktop/DBus; interface=org.freedesktop.DBus; member=NameAcquired
   string ":1.366"
```
it does acquire dbus however

**Comment by 029A-h** [comment]
As far as I understand on Jan 25 beeep notification was removed from application. 
[COMMIT: refactor: remove notifications feature](https://github.com/ayntgl/discordo/commit/d984d087a2e451c25e4de15ed39e858c8f5e64cc)

What is current status of notification feature? Is it still fully removed or does it works anyhow on linux?
I'm asking because in that case the app is moreless useless for my need. README.md contains desktop notification among features.

**Comment by sewnie** [comment]
i still dont get notifications
