### ISSUE TITLE
Typing not working after update...?

### ISSUE THREAD

**Issue by dagleykd** [rigormorrtiss/discordo#374]
Hi all - haven't updated the copy of Discordo I have on my little MX Linux laptop for a few weeks. Just downloaded the latest pre-built version and I cannot type in the chatbox?

I've tried loading Discordo in XFCE Terminal and cool-retro-term and it doesn't work in either...?

**Comment by cyberme0w** [comment]
This is likely due to the new 'insert' mode, which tries to simulate how vim feels. Try hitting 'i' inside the input box before typing.

**Comment by dagleykd** [comment]
Oh...not sure I like that at all...I'll deal if need be, but that just seems like an odd choice in my eyes considering no webchat programs that I can think of (Messenger, Discord, Hexchat, Slack, etc) function that way in the sense you need to hit a given key before you can type your message...?

Seeing as discordo isn't a text editor like vim...just curious why that 'insert mode' was brought about...?

Is there a way to disable it and go back to simply being able to type in the chat box as with standard Discord?

Thanks for the quick reply!

**EDIT - Just redownloaded the new version and it seems I only have to hit 'i' once and then it works normally with 'just typing' again...? Even if I switch servers / chats, etc? Is that intentional? If so, and you only have to hit the 'i' key once and then it stays turned on while the program is open, it seems like an odd requirement?

Not trying to sound ungrateful, by the way, I love Discordo - it's great on my little HP Stream with only 4GB of RAM as most of the time I am only typing messages and it saves on SO much RAM use compared to the stock Discord client! :)

Just wondering what the reasoning behind the feature is and glad that somebody was kind enough to explain to me how to get Discordo 'working again' even when there wasn't anything wrong! ;)**

**Comment by cyberme0w** [comment]
My guess is it got implemented because it was requested and nobody opposed it. It also strikes me as an odd feature, given how messages can be edited in vim/any other editor already (Ctrl+E with default keybinds).

An 'on/off' toggle would be great, but sadly there isn't one. If you want the old behavior, I would suggest downgrading your local version of discordo to the commit before the vi-interface was added (`git checkout ff7dbd15c5c637fb084254e2d1bcd28241c429da`) and recompiling it.

The Message Input staying in Insert mode after going back and forth between different UI elements does sound like a bug to me. Perhaps it would make sense to open an issue related to that. Worst case scenario, it'll get closed with 'perceived bug was in fact feature' ^^
