### ISSUE TITLE
Is it possible to view unlimited messages from the past?

### ISSUE THREAD

**Issue by SebastianMpl** [rigormorrtiss/discordo#402]
Hi, I played a little with discordo and it is simply awesome.
However I would like to go back in messages history so that they could be loaded as I go backward.
Currently I can set messages_limit which is uint8 go type, so I switched to uint16 and messages_limit 500 but it still don't go as far. Is it made intentionally to not ban users abusing API?
Could you please advice?

EDIT: It seems that it occurs in "pure" terminal (CTRL+ALT+F2) where scrolling with touchpad is unavailable. In terminal in GUI I can scroll more messages but the k key still does not go far back.

Thank you,

**Comment by ayn2op** [comment]
The maximum number of messages that can be fetched from the API at a time is 100. Discord API does have a way to fetch more messages by specifying different parameters, but that’s not implemented in Discordo yet, mainly because the TextView widget used to display the messages is too slow for this application.

**Comment by SebastianMpl** [comment]
Thank you very much for explanation.

**Comment by ayn2op** [comment]
@SebastianMpl https://github.com/ayn2op/discordo/pull/716
